### PR TITLE
Add `showChangelogOption` message

### PR DESCRIPTION
**Pull request by Nerixyz**
See mozilla/firefox-translations#498.

### CODE REVIEW

**Review by flodolo — CHANGES_REQUESTED** [review]
Please only add en-US strings, don't touch other locales even if it seems logical to do it (those will go through Pontoon).

**Comment by Nerixyz** [comment]
> Please only add en-US strings, don't touch other locales even if it seems logical to do it (those will go through Pontoon).

Sorry, I didn't know how it's really done. Maybe this should be mentioned in the readme?

**Comment by flodolo** [comment]
> Sorry, I didn't know how it's really done. Maybe this should be mentioned in the readme?

That's a good point, but it would be for [this repo](https://github.com/mozilla/firefox-translations) ;-) 

Also, note that we need agreement on that feature before asking volunteers to localize this string. I don't see anything yet in the PR, and the connected issue doesn't have a lot of agreement.

**Comment by andrenatal** [comment]
Can we have this landed?

**Review by flodolo — APPROVED** [review]

**Comment by flodolo** [comment]
Yes, it was waiting for the feature to be actually approved in the add-on.

**Pull request merged**
