### PR TITLE
Change quality estimation message

### LINKED ISSUE #326: It's not clear what "Enable quality estimation" does
I ticked "Enable quality estimation", but I don't see an estimate anywhere. Either it's intended for users, in which case it might be placed somewhere more obvious, or it's intended to provide feedback to the developers, in which case that might need to be made more obvious.

The only change I did notice was that the title of a page doesn't get translated, which I was about to report until I found https://github.com/mozilla/firefox-translations/pull/221.

### PR DESCRIPTION
**Pull request by andrenatal**
fixes https://github.com/mozilla/firefox-translations/issues/326

@flodolo I'm not sure if this is the best way to replace the messages, but we need to change it per this comment: https://github.com/mozilla/firefox-translations/issues/326#issuecomment-1131510640
Thank you.

### CODE REVIEW

**Comment by andrenatal** [comment]
And there will be no further changes, you can already merge it if the PR is correct. If there's further questions about the message, @kpu is the right person to address.

**Review by flodolo — CHANGES_REQUESTED** [review]
This is not correct.

1) Never touch other locales, that's Pontoon's role.
2) When you update a string, you need to use a new ID. https://mozilla-l10n.github.io/documentation/localization/making_string_changes.html

This PR should only include one change to the en_US file, with a new ID.

**Comment by andrenatal** [comment]
@flodolo ok, fixed

**Review by flodolo — COMMENTED** [review]
Do you still need the string that you removed in the first version of this PR (`qualityEstimationMessage`)? If not, you should remove it in this PR.

**Review by flodolo — APPROVED** [review]

**Pull request merged**
